channels:
- conda-forge
dependencies:
- python=3.10.14
- pip<=24.0
- pip:
  - mlflow==2.12.1
  - astunparse==1.6.3
  - cloudpickle==3.0.0
  - dill==0.3.8
  - numpy==1.26.4
  - packaging==24.0
  - pandas==2.2.1
  - pynvml==11.5.0
  - pyyaml==6.0.1
  - torch==2.1.1
  - tqdm==4.65.0
name: mlflow-env
